version: '3.8'

services:
  ingestion_component:
    build:
      context: .
      dockerfile: dockerfile
    networks:
      - ingestion_component
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
    command: python manage.py runserver
    restart: always

networks:
  ingestion_component: