# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - cemex-servicenow-rag-rcataldi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    # Defines the overall strategy parameters for the build job
    strategy:
      fail-fast: false
      matrix: # The set of configuration parameters that the job will use
        python-version: ["3.10", "3.11", "3.12"]
        poetry-version: ["1.2.2"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and add Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install the project dependencies
        run: poetry install

      - name: Zip artifact for deployment
        run: zip skapp.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: skapp
          path: |
            skapp.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: skapp

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B113C46FB94642F99294A4C8AABEBDC5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F74DCD768C9541B69A773650F7B1AD1D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D542B6788A4A4B8792EA4E77223F787A }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'ai-sandbox-rcataldi'
          slot-name: 'Production'
